OptimaFarmTaskCore/Models/EmployeeModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using OptimaFarmTaskCore.Repositories;

namespace OptimaFarmTaskCore.Models
{
    public class EmployeeModel
    {
        public EmployeeModel()
        {
            Id = IdGenerator.Generate();
        }

        public int Id { get; set; }
        
        public string Name { get; set; }
        public string Surname { get; set; }

        public int Salary { get; set; }
    }
}

OptimaFarmTaskCore/Models/ErrorViewModel.cs
using System;

namespace OptimaFarmTaskCore.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

OptimaFarmTaskCore/Models/UserSearchModel.cs
namespace OptimaFarmTaskCore.Models
{
    public class UserSearchModel
    {
        public string SearchFieldData { get; set; }
    }
}

OptimaFarmTaskCore/Controllers/OptimaFarmController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using OptimaFarmTaskCore.Models;
using OptimaFarmTaskCore.Repositories;

namespace OptimaFarmTaskCore.Controllers
{
    public class OptimaFarmController : Controller
    {

        public OptimaFarmController()
        {
        }

        public IActionResult Index()
        {
            return View(EmployeeRepository.Employees);
        }

        public IActionResult CreateEmployee()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateEmployee([Bind("Id,Name,Surname,Salary")]EmployeeModel employee)
        {
            Add(employee);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int? id)
        {
            Remove(id);
            return RedirectToAction("Index");
        }

        public IActionResult Details(int? id)
        {
            return View(FindById(id));
        }

        public IActionResult Statistics()
        {
            int max = 0, min = 0;
            int avg = 0;
            EmployeeModel minEmployee = new EmployeeModel(), maxEmployee = new EmployeeModel();

            foreach (var employee in EmployeeRepository.Employees)
            {
                if (employee.Salary > max)
                {
                    max = employee.Salary;
                    maxEmployee = employee;
                }
                else if(employee.Salary < min)
                {
                    min = employee.Salary;
                    minEmployee = employee;
                }

                avg += employee.Salary;
            }

            ViewData["max"] = max;
            ViewData["min"] = min;

            ViewData["employeeCount"] = EmployeeRepository.Employees.Count;
            ViewData["avg"] = avg / EmployeeRepository.Employees.Count;

            ViewData["minEmployee"] = minEmployee;
            ViewData["maxEmployee"] = maxEmployee;

            return View();
        }

        [HttpPost]
        public IActionResult Search(string searchString)
        {
            return View(Find(searchString));
        }


        //Employee Actions
        private List<EmployeeModel> Find(string nameOrSurname)
        {
            return EmployeeRepository.Employees
                .Where(e => e.Name.Contains(nameOrSurname) || e.Surname.Contains(nameOrSurname))
                .ToList();
        }

        private EmployeeModel FindById(int? id)
        {
            return EmployeeRepository.Employees.FirstOrDefault(e => e.Id == id);
        }

        private bool Add(EmployeeModel employee)
        {
            if (FindById(employee.Id) != null)
            {
                return false;
            }
            EmployeeRepository.Employees.Add(employee);
            return true;
        }

        private bool Remove(int? id)
        {
            EmployeeRepository.Employees.Remove(EmployeeRepository.Employees.First(e => e.Id == id));
            return true;
        }
    }
}

OptimaFarmTaskCore/Views/OptimaFarm/CreateEmployee.cshtml
@model OptimaFarmTaskCore.Models.EmployeeModel
@{
    ViewData["Title"] = "Create Employee";
}

<h1>Create Employee</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateEmployee">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>

                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salary" class="control-label"></label>
                <input asp-for="Salary" class="form-control" />
                <span asp-validation-for="Salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create User" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

OptimaFarmTaskCore/Views/OptimaFarm/Details.cshtml
@model EmployeeModel

@{
    ViewBag.Title = Model.Name + " " + Model.Surname;
}

<h2>Details</h2>

<div class="model-info">
    <ul>
        <li>Name: @Html.DisplayFor(modelItem => modelItem.Name)</li>
        <li>Surname: @Html.DisplayFor(modelItem => modelItem.Surname)</li>
        <li>Salary(in USD): @Html.DisplayFor(modelItem => modelItem.Salary)</li>
    </ul>
</div>

<a asp-action="Index">Back to Home page</a>

OptimaFarmTaskCore/Views/OptimaFarm/Index.cshtml
@model IEnumerable<OptimaFarmTaskCore.Models.EmployeeModel>

@{
    ViewData["Title"] = "Optima Farm Employee List";
}


    <form asp-controller="OptimaFarm" asp-action="Search">
        <p>
            Enter name or Surname: <input type="text" name="SearchString">
            <input type="submit" value="Find" />
        </p>
    </form>

<p>
    <a asp-action="CreateEmployee">Create New</a>
</p>
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Surname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Salary)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Surname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salary)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
    }
    </tbody>
</table>

OptimaFarmTaskCore/Views/OptimaFarm/Search.cshtml
@model IEnumerable<OptimaFarmTaskCore.Models.EmployeeModel>

@{
    ViewBag.Title = "Search Results";
    Layout = "_Layout";
}

<h2>Search results:</h2>

@foreach(var employee in Model)
{
    <table class="table">
        <tr>
            <td>Name</td>
            <td>Surname</td>
            <td>Salary</td>
        </tr>
        <tr>
            <td>
                @Html.DisplayFor(modelItem => employee.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => employee.Surname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => employee.Salary)
            </td>
        </tr>

    </table>
    
}

OptimaFarmTaskCore/Views/OptimaFarm/Statistics.cshtml
@{
    ViewBag.Title = "Optima Farm Employee Stats";
    Layout = "_Layout";
}

<h2>Optima Farm Employee Statistics</h2>

<h4>Employee Stats:</h4>

<p>Employee number: @ViewData["employeeCount"]</p>
<p>Average salary for employee: @ViewData["avg"]</p>
<p>Highest salary: @ViewData["max"]</p>
<p>Lowest salary: @ViewData["min"]</p>

OptimaFarmTaskCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Optima Farm Task</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="OptimaFarm" asp-action="Index">Optima Farm</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="OptimaFarm" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="OptimaFarm" asp-action="Statistics">Statistics</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - OptimaFarmTaskCore
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>